name: ezy_orders_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & Architecture
  provider: ^6.1.2
  get_it: ^7.7.0
  go_router: ^14.2.0

  # Networking
  http: ^1.6.0

  # UI & UX
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.3.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10
  carousel_slider: ^5.0.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  fluttertoast: ^8.2.6
  dots_indicator: ^3.0.0
  cupertino_icons: ^1.0.8
  flutter_html: ^3.0.0
  html: ^0.15.4

  # Feature Integrations
  mobile_scanner: ^5.1.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0
  razorpay_flutter: ^1.3.7
  flutter_pdfview: ^1.3.4
  share_plus: ^10.0.0
  package_info_plus: ^8.0.0

  # Data & Local Storage
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.4

  # Utils
  logger: ^2.4.0
  intl: ^0.19.0
  flutter_cache_manager: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # build_runner: ^2.4.13 # Kept just in case, but unused for now


flutter:
  uses-material-design: true
  assets:
    - assets/images/
#    - assets/svgs/
